steps:
  - label: "Presubmit"
    commands:
    - make lint
    - scripts/gen-diff.sh
    plugins:
      - file:///buildkite/plugins/docker:
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/cloud/waas-client-library-go/presubmit:latest
          always-pull: true
          propagate-environment: true
          propagate-uid-gid: true
    agents:
      queue: docker
