// Code generated by ifacemaker. DO NOT EDIT.

package v1

import (
	"context"

	poolspb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/pools/v1"
	"github.com/googleapis/gax-go/v2"
	"google.golang.org/grpc"
)

// PoolServiceClient is a generated interface for pools protoc-gen-go_gapic client poolServiceClient.
type PoolServiceClient interface {
	// Close closes the connection to the API service. The user should invoke this when
	// the client is no longer required.
	Close() error
	// Connection returns a connection to the API service.
	//
	// Deprecated: Connections are now pooled so this method does not always
	// return the same resource.
	Connection() *grpc.ClientConn
	// CreatePool creates a Pool. Call this method before creating any resources scoped to
	// a Pool.
	CreatePool(ctx context.Context, req *poolspb.CreatePoolRequest, opts ...gax.CallOption) (*poolspb.Pool, error)
	// GetPool gets a Pool.
	GetPool(ctx context.Context, req *poolspb.GetPoolRequest, opts ...gax.CallOption) (*poolspb.Pool, error)
	// ListPools lists the Pools of an Address. The Address must belong to a Pool.
	ListPools(ctx context.Context, req *poolspb.ListPoolsRequest, opts ...gax.CallOption) PoolIterator
}
