// Code generated by ifacemaker. DO NOT EDIT.

package v1

import (
	"context"

	mpc_walletspb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/mpc_wallets/v1"
	"github.com/googleapis/gax-go/v2"
)

// ClientWrappedCreateMPCWalletOperation is a generated interface for mpcwallet protoc-gen-go_gapic client WrappedCreateMPCWalletOperation.
type ClientWrappedCreateMPCWalletOperation interface {
	// PathPrefix returns the path prefix for the operation to be used in HTTP requests.
	// E.g. if the path prefix is `/waas/mpc_wallets`, then the request path would be:
	// `/waas/mpc_wallets/v1/operations/<operationId>`.
	PathPrefix() string
	// Wait delegates to the wrapped longrunning CreateMPCWalletOperation with the
	// override LRO options and handling unwrapping client errors.
	Wait(ctx context.Context, opts ...gax.CallOption) (*mpc_walletspb.MPCWallet, error)
	// Poll delegates to the wrapped longrunning CreateMPCWalletOperation with the
	// override LRO options and handling unwrapping client errors.
	Poll(ctx context.Context, opts ...gax.CallOption) (*mpc_walletspb.MPCWallet, error)
	// Metadata delegates to the wrapped longrunning CreateMPCWalletOperation.
	Metadata() (*mpc_walletspb.CreateMPCWalletMetadata, error)
	// Done delegates to the wrapped longrunning CreateMPCWalletOperation.
	Done() bool
	// Name delegates to the wrapped longrunning CreateMPCWalletOperation.
	Name() string
}
