// Code generated by ifacemaker. DO NOT EDIT.

package v1

import (
	"context"

	"cloud.google.com/go/longrunning/autogen/longrunningpb"
	mpc_walletspb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/mpc_wallets/v1"
	"github.com/googleapis/gax-go/v2"
	"google.golang.org/grpc"
)

// MPCWalletServiceClient is a generated interface for mpcwallet protoc-gen-go_gapic client mpcWalletServiceClient.
type MPCWalletServiceClient interface {
	// Close closes the connection to the API service. The user should invoke this when
	// the client is no longer required.
	Close() error
	// Connection returns a connection to the API service.
	//
	// Deprecated: Connections are now pooled so this method does not always
	// return the same resource.
	Connection() *grpc.ClientConn
	// GetOperation gets the latest state of a long-running operation.
	GetOperation(ctx context.Context, req *longrunningpb.GetOperationRequest, opts ...gax.CallOption) (*longrunningpb.Operation, error)
	// CreateMPCWallet creates an MPCWallet. The Device in the request must have been registered
	// using MPCKeyService’s RegisterDevice before this method is called. Under the hood, this
	// calls MPCKeyService’s CreateDeviceGroup with the appropriate parameters. After calling this,
	// use MPCKeyService’s ListMPCOperations to poll for the pending CreateDeviceGroup operation,
	// and use the WaaS SDK’s ComputeMPCOperation to complete the operation.
	CreateMPCWallet(ctx context.Context, req *mpc_walletspb.CreateMPCWalletRequest, opts ...gax.CallOption) (ClientWrappedCreateMPCWalletOperation, error)
	// CreateMPCWalletOperation returns the CreateMPCWalletOperation indicated by the given name.
	CreateMPCWalletOperation(name string) ClientWrappedCreateMPCWalletOperation
	// GetMPCWallet gets an MPCWallet.
	GetMPCWallet(ctx context.Context, req *mpc_walletspb.GetMPCWalletRequest, opts ...gax.CallOption) (*mpc_walletspb.MPCWallet, error)
	// ListMPCWallets lists MPCWallets.
	ListMPCWallets(ctx context.Context, req *mpc_walletspb.ListMPCWalletsRequest, opts ...gax.CallOption) MPCWalletIterator
	// GenerateAddress generates an Address within an MPCWallet.
	GenerateAddress(ctx context.Context, req *mpc_walletspb.GenerateAddressRequest, opts ...gax.CallOption) (*mpc_walletspb.Address, error)
	// GetAddress gets an Address.
	GetAddress(ctx context.Context, req *mpc_walletspb.GetAddressRequest, opts ...gax.CallOption) (*mpc_walletspb.Address, error)
	// ListAddresses lists Addresses within an MPCWallet.
	ListAddresses(ctx context.Context, req *mpc_walletspb.ListAddressesRequest, opts ...gax.CallOption) AddressIterator
	// ListBalances lists Balances.
	ListBalances(ctx context.Context, req *mpc_walletspb.ListBalancesRequest, opts ...gax.CallOption) BalanceIterator
	// ListBalanceDetails lists BalanceDetails.
	ListBalanceDetails(ctx context.Context, req *mpc_walletspb.ListBalanceDetailsRequest, opts ...gax.CallOption) BalanceDetailIterator
}
