// Code generated by ifacemaker. DO NOT EDIT.

package v1

import (
	"context"

	mpc_transactionspb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/mpc_transactions/v1"
	"github.com/googleapis/gax-go/v2"
)

// ClientWrappedCreateMPCTransactionOperation is a generated interface for mpctransaction protoc-gen-go_gapic client WrappedCreateMPCTransactionOperation.
type ClientWrappedCreateMPCTransactionOperation interface {
	// PathPrefix returns the path prefix for the operation to be used in HTTP requests.
	// E.g. if the path prefix is `/waas/mpc_transactions`, then the request path would be:
	// `/waas/mpc_transactions/v1/operations/<operationId>`.
	PathPrefix() string
	// Wait delegates to the wrapped longrunning CreateMPCTransactionOperation with the
	// override LRO options and handling unwrapping client errors.
	Wait(ctx context.Context, opts ...gax.CallOption) (*mpc_transactionspb.MPCTransaction, error)
	// Poll delegates to the wrapped longrunning CreateMPCTransactionOperation with the
	// override LRO options and handling unwrapping client errors.
	Poll(ctx context.Context, opts ...gax.CallOption) (*mpc_transactionspb.MPCTransaction, error)
	// Metadata delegates to the wrapped longrunning CreateMPCTransactionOperation.
	Metadata() (*mpc_transactionspb.CreateMPCTransactionMetadata, error)
	// Done delegates to the wrapped longrunning CreateMPCTransactionOperation.
	Done() bool
	// Name delegates to the wrapped longrunning CreateMPCTransactionOperation.
	Name() string
}
