// Code generated by ifacemaker. DO NOT EDIT.

package v1

import (
	"context"

	protocolspb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/protocols/v1"
	typespb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/types/v1"
	"github.com/googleapis/gax-go/v2"
	"google.golang.org/grpc"
)

// ProtocolServiceClient is a generated interface for protocols protoc-gen-go_gapic client protocolServiceClient.
type ProtocolServiceClient interface {
	// Close closes the connection to the API service. The user should invoke this when
	// the client is no longer required.
	Close() error
	// Connection returns a connection to the API service.
	//
	// Deprecated: Connections are now pooled so this method does not always
	// return the same resource.
	Connection() *grpc.ClientConn
	// ConstructTransaction constructs an unsigned transaction. The payloads in the
	// required_signatures of the returned Transaction must be signed before the Transaction
	// is broadcast.
	ConstructTransaction(ctx context.Context, req *protocolspb.ConstructTransactionRequest, opts ...gax.CallOption) (*typespb.Transaction, error)
	// ConstructTransferTransaction constructs an unsigned transfer transaction.
	// A transfer transaction is a transaction that moves an Asset from one Address to another.
	// The payloads in the required_signatures of the returned Transaction must be signed before
	// the Transaction is broadcast.
	ConstructTransferTransaction(ctx context.Context, req *protocolspb.ConstructTransferTransactionRequest, opts ...gax.CallOption) (*typespb.Transaction, error)
	// BroadcastTransaction broadcasts a transaction to a node in the Network.
	BroadcastTransaction(ctx context.Context, req *protocolspb.BroadcastTransactionRequest, opts ...gax.CallOption) (*typespb.Transaction, error)
	// EstimateFee estimates the current network fee for the specified Network. For EVM Networks, this
	// corresponds to the gas_price, max_fee_per_gas, and max_priority_fee_per_gas.
	EstimateFee(ctx context.Context, req *protocolspb.EstimateFeeRequest, opts ...gax.CallOption) (*protocolspb.EstimateFeeResponse, error)
}
