// Code generated by ifacemaker. DO NOT EDIT.

package v1

import (
	"context"

	mpc_keyspb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/mpc_keys/v1"
	"github.com/googleapis/gax-go/v2"
)

// ClientWrappedPrepareDeviceArchiveOperation is a generated interface for mpckey protoc-gen-go_gapic client WrappedPrepareDeviceArchiveOperation.
type ClientWrappedPrepareDeviceArchiveOperation interface {
	// PathPrefix returns the path prefix for the operation to be used in HTTP requests.
	// E.g. if the path prefix is `/waas/mpc_keys`, then the request path would be:
	// `/waas/mpc_keys/v1/operations/<operationId>`.
	PathPrefix() string
	// Wait delegates to the wrapped longrunning PrepareDeviceArchiveOperation with the
	// override LRO options and handling unwrapping client errors.
	Wait(ctx context.Context, opts ...gax.CallOption) (*mpc_keyspb.DeviceGroup, error)
	// Poll delegates to the wrapped longrunning PrepareDeviceArchiveOperation with the
	// override LRO options and handling unwrapping client errors.
	Poll(ctx context.Context, opts ...gax.CallOption) (*mpc_keyspb.DeviceGroup, error)
	// Metadata delegates to the wrapped longrunning PrepareDeviceArchiveOperation.
	Metadata() (*mpc_keyspb.PrepareDeviceArchiveMetadata, error)
	// Done delegates to the wrapped longrunning PrepareDeviceArchiveOperation.
	Done() bool
	// Name delegates to the wrapped longrunning PrepareDeviceArchiveOperation.
	Name() string
}
