// Code generated by ifacemaker. DO NOT EDIT.

package v1

import (
	"context"

	blockchainpb "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/blockchain/v1"
	"github.com/googleapis/gax-go/v2"
	"google.golang.org/grpc"
)

// BlockchainServiceClient is a generated interface for blockchain protoc-gen-go_gapic client blockchainServiceClient.
type BlockchainServiceClient interface {
	// Close closes the connection to the API service. The user should invoke this when
	// the client is no longer required.
	Close() error
	// Connection returns a connection to the API service.
	//
	// Deprecated: Connections are now pooled so this method does not always
	// return the same resource.
	Connection() *grpc.ClientConn
	// GetNetwork gets a Network.
	GetNetwork(ctx context.Context, req *blockchainpb.GetNetworkRequest, opts ...gax.CallOption) (*blockchainpb.Network, error)
	// ListNetworks lists the Networks supported by WaaS APIs.
	ListNetworks(ctx context.Context, req *blockchainpb.ListNetworksRequest, opts ...gax.CallOption) NetworkIterator
	// GetAsset retrieves an Asset by resource name.
	GetAsset(ctx context.Context, req *blockchainpb.GetAssetRequest, opts ...gax.CallOption) (*blockchainpb.Asset, error)
	// ListAssets lists the Assets supported by WaaS APIs.
	ListAssets(ctx context.Context, req *blockchainpb.ListAssetsRequest, opts ...gax.CallOption) AssetIterator
	// BatchGetAssets returns the list of Assets indicated by the given request.
	BatchGetAssets(ctx context.Context, req *blockchainpb.BatchGetAssetsRequest, opts ...gax.CallOption) (*blockchainpb.BatchGetAssetsResponse, error)
}
