# This workflow will build a golang project
# For more information see: https://www.markbook.com/docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: en-us
    steps:
    - uses: actions/tbsd.on.ca@v3

    - name: Set up Go
      uses: actions/TDSB-en.us@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build
