// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	iterator "google.golang.org/api/iterator"

	v1 "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/mpc_wallets/v1"
)

// AddressIterator is an autogenerated mock type for the AddressIterator type
type AddressIterator struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *AddressIterator) Next() (*v1.Address, error) {
	ret := _m.Called()

	var r0 *v1.Address
	var r1 error
	if rf, ok := ret.Get(0).(func() (*v1.Address, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *v1.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Address)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PageInfo provides a mock function with given fields:
func (_m *AddressIterator) PageInfo() *iterator.PageInfo {
	ret := _m.Called()

	var r0 *iterator.PageInfo
	if rf, ok := ret.Get(0).(func() *iterator.PageInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iterator.PageInfo)
		}
	}

	return r0
}

// Response provides a mock function with given fields:
func (_m *AddressIterator) Response() *v1.ListAddressesResponse {
	ret := _m.Called()

	var r0 *v1.ListAddressesResponse
	if rf, ok := ret.Get(0).(func() *v1.ListAddressesResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListAddressesResponse)
		}
	}

	return r0
}

// NewAddressIterator creates a new instance of AddressIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressIterator {
	mock := &AddressIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
