// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	clientsv1 "github.com/coinbase/waas-client-library-go/clients/v1"

	gax "github.com/googleapis/gax-go/v2"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/blockchain/v1"
)

// BlockchainServiceClient is an autogenerated mock type for the BlockchainServiceClient type
type BlockchainServiceClient struct {
	mock.Mock
}

// BatchGetAssets provides a mock function with given fields: ctx, req, opts
func (_m *BlockchainServiceClient) BatchGetAssets(ctx context.Context, req *v1.BatchGetAssetsRequest, opts ...gax.CallOption) (*v1.BatchGetAssetsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.BatchGetAssetsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BatchGetAssetsRequest, ...gax.CallOption) (*v1.BatchGetAssetsResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BatchGetAssetsRequest, ...gax.CallOption) *v1.BatchGetAssetsResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BatchGetAssetsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.BatchGetAssetsRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *BlockchainServiceClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection provides a mock function with given fields:
func (_m *BlockchainServiceClient) Connection() *grpc.ClientConn {
	ret := _m.Called()

	var r0 *grpc.ClientConn
	if rf, ok := ret.Get(0).(func() *grpc.ClientConn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.ClientConn)
		}
	}

	return r0
}

// GetAsset provides a mock function with given fields: ctx, req, opts
func (_m *BlockchainServiceClient) GetAsset(ctx context.Context, req *v1.GetAssetRequest, opts ...gax.CallOption) (*v1.Asset, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetAssetRequest, ...gax.CallOption) (*v1.Asset, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetAssetRequest, ...gax.CallOption) *v1.Asset); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetAssetRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNetwork provides a mock function with given fields: ctx, req, opts
func (_m *BlockchainServiceClient) GetNetwork(ctx context.Context, req *v1.GetNetworkRequest, opts ...gax.CallOption) (*v1.Network, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.Network
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetNetworkRequest, ...gax.CallOption) (*v1.Network, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetNetworkRequest, ...gax.CallOption) *v1.Network); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Network)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetNetworkRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAssets provides a mock function with given fields: ctx, req, opts
func (_m *BlockchainServiceClient) ListAssets(ctx context.Context, req *v1.ListAssetsRequest, opts ...gax.CallOption) clientsv1.AssetIterator {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 clientsv1.AssetIterator
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ListAssetsRequest, ...gax.CallOption) clientsv1.AssetIterator); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientsv1.AssetIterator)
		}
	}

	return r0
}

// ListNetworks provides a mock function with given fields: ctx, req, opts
func (_m *BlockchainServiceClient) ListNetworks(ctx context.Context, req *v1.ListNetworksRequest, opts ...gax.CallOption) clientsv1.NetworkIterator {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 clientsv1.NetworkIterator
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ListNetworksRequest, ...gax.CallOption) clientsv1.NetworkIterator); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientsv1.NetworkIterator)
		}
	}

	return r0
}

// NewBlockchainServiceClient creates a new instance of BlockchainServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockchainServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockchainServiceClient {
	mock := &BlockchainServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
