// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gax "github.com/googleapis/gax-go/v2"
	mock "github.com/stretchr/testify/mock"

	mpc_keysv1 "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/mpc_keys/v1"
)

// ClientWrappedCreateDeviceGroupOperation is an autogenerated mock type for the ClientWrappedCreateDeviceGroupOperation type
type ClientWrappedCreateDeviceGroupOperation struct {
	mock.Mock
}

// Done provides a mock function with given fields:
func (_m *ClientWrappedCreateDeviceGroupOperation) Done() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Metadata provides a mock function with given fields:
func (_m *ClientWrappedCreateDeviceGroupOperation) Metadata() (*mpc_keysv1.CreateDeviceGroupMetadata, error) {
	ret := _m.Called()

	var r0 *mpc_keysv1.CreateDeviceGroupMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func() (*mpc_keysv1.CreateDeviceGroupMetadata, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *mpc_keysv1.CreateDeviceGroupMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mpc_keysv1.CreateDeviceGroupMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *ClientWrappedCreateDeviceGroupOperation) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PathPrefix provides a mock function with given fields:
func (_m *ClientWrappedCreateDeviceGroupOperation) PathPrefix() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Poll provides a mock function with given fields: ctx, opts
func (_m *ClientWrappedCreateDeviceGroupOperation) Poll(ctx context.Context, opts ...gax.CallOption) (*mpc_keysv1.DeviceGroup, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *mpc_keysv1.DeviceGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...gax.CallOption) (*mpc_keysv1.DeviceGroup, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...gax.CallOption) *mpc_keysv1.DeviceGroup); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mpc_keysv1.DeviceGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...gax.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Wait provides a mock function with given fields: ctx, opts
func (_m *ClientWrappedCreateDeviceGroupOperation) Wait(ctx context.Context, opts ...gax.CallOption) (*mpc_keysv1.DeviceGroup, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *mpc_keysv1.DeviceGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...gax.CallOption) (*mpc_keysv1.DeviceGroup, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...gax.CallOption) *mpc_keysv1.DeviceGroup); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mpc_keysv1.DeviceGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...gax.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientWrappedCreateDeviceGroupOperation creates a new instance of ClientWrappedCreateDeviceGroupOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWrappedCreateDeviceGroupOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWrappedCreateDeviceGroupOperation {
	mock := &ClientWrappedCreateDeviceGroupOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
