// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gax "github.com/googleapis/gax-go/v2"
	grpc "google.golang.org/grpc"

	longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"

	mock "github.com/stretchr/testify/mock"

	mpc_transactionsv1 "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/mpc_transactions/v1"

	v1 "github.com/coinbase/waas-client-library-go/clients/v1"
)

// MPCTransactionServiceClient is an autogenerated mock type for the MPCTransactionServiceClient type
type MPCTransactionServiceClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MPCTransactionServiceClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection provides a mock function with given fields:
func (_m *MPCTransactionServiceClient) Connection() *grpc.ClientConn {
	ret := _m.Called()

	var r0 *grpc.ClientConn
	if rf, ok := ret.Get(0).(func() *grpc.ClientConn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.ClientConn)
		}
	}

	return r0
}

// CreateMPCTransaction provides a mock function with given fields: ctx, req, opts
func (_m *MPCTransactionServiceClient) CreateMPCTransaction(ctx context.Context, req *mpc_transactionsv1.CreateMPCTransactionRequest, opts ...gax.CallOption) (v1.ClientWrappedCreateMPCTransactionOperation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 v1.ClientWrappedCreateMPCTransactionOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *mpc_transactionsv1.CreateMPCTransactionRequest, ...gax.CallOption) (v1.ClientWrappedCreateMPCTransactionOperation, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *mpc_transactionsv1.CreateMPCTransactionRequest, ...gax.CallOption) v1.ClientWrappedCreateMPCTransactionOperation); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ClientWrappedCreateMPCTransactionOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *mpc_transactionsv1.CreateMPCTransactionRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMPCTransactionOperation provides a mock function with given fields: name
func (_m *MPCTransactionServiceClient) CreateMPCTransactionOperation(name string) v1.ClientWrappedCreateMPCTransactionOperation {
	ret := _m.Called(name)

	var r0 v1.ClientWrappedCreateMPCTransactionOperation
	if rf, ok := ret.Get(0).(func(string) v1.ClientWrappedCreateMPCTransactionOperation); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ClientWrappedCreateMPCTransactionOperation)
		}
	}

	return r0
}

// GetMPCTransaction provides a mock function with given fields: ctx, req, opts
func (_m *MPCTransactionServiceClient) GetMPCTransaction(ctx context.Context, req *mpc_transactionsv1.GetMPCTransactionRequest, opts ...gax.CallOption) (*mpc_transactionsv1.MPCTransaction, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *mpc_transactionsv1.MPCTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *mpc_transactionsv1.GetMPCTransactionRequest, ...gax.CallOption) (*mpc_transactionsv1.MPCTransaction, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *mpc_transactionsv1.GetMPCTransactionRequest, ...gax.CallOption) *mpc_transactionsv1.MPCTransaction); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mpc_transactionsv1.MPCTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *mpc_transactionsv1.GetMPCTransactionRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOperation provides a mock function with given fields: ctx, req, opts
func (_m *MPCTransactionServiceClient) GetOperation(ctx context.Context, req *longrunningpb.GetOperationRequest, opts ...gax.CallOption) (*longrunningpb.Operation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *longrunningpb.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *longrunningpb.GetOperationRequest, ...gax.CallOption) (*longrunningpb.Operation, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *longrunningpb.GetOperationRequest, ...gax.CallOption) *longrunningpb.Operation); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*longrunningpb.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *longrunningpb.GetOperationRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMPCTransactions provides a mock function with given fields: ctx, req, opts
func (_m *MPCTransactionServiceClient) ListMPCTransactions(ctx context.Context, req *mpc_transactionsv1.ListMPCTransactionsRequest, opts ...gax.CallOption) v1.MPCTransactionIterator {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 v1.MPCTransactionIterator
	if rf, ok := ret.Get(0).(func(context.Context, *mpc_transactionsv1.ListMPCTransactionsRequest, ...gax.CallOption) v1.MPCTransactionIterator); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.MPCTransactionIterator)
		}
	}

	return r0
}

// NewMPCTransactionServiceClient creates a new instance of MPCTransactionServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMPCTransactionServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MPCTransactionServiceClient {
	mock := &MPCTransactionServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
