// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	iterator "google.golang.org/api/iterator"

	v1 "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/blockchain/v1"
)

// NetworkIterator is an autogenerated mock type for the NetworkIterator type
type NetworkIterator struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *NetworkIterator) Next() (*v1.Network, error) {
	ret := _m.Called()

	var r0 *v1.Network
	var r1 error
	if rf, ok := ret.Get(0).(func() (*v1.Network, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *v1.Network); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Network)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PageInfo provides a mock function with given fields:
func (_m *NetworkIterator) PageInfo() *iterator.PageInfo {
	ret := _m.Called()

	var r0 *iterator.PageInfo
	if rf, ok := ret.Get(0).(func() *iterator.PageInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iterator.PageInfo)
		}
	}

	return r0
}

// Response provides a mock function with given fields:
func (_m *NetworkIterator) Response() *v1.ListNetworksResponse {
	ret := _m.Called()

	var r0 *v1.ListNetworksResponse
	if rf, ok := ret.Get(0).(func() *v1.ListNetworksResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListNetworksResponse)
		}
	}

	return r0
}

// NewNetworkIterator creates a new instance of NetworkIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetworkIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetworkIterator {
	mock := &NetworkIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
