// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gax "github.com/googleapis/gax-go/v2"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	typesv1 "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/types/v1"

	v1 "github.com/coinbase/waas-client-library-go/gen/go/coinbase/cloud/protocols/v1"
)

// ProtocolServiceClient is an autogenerated mock type for the ProtocolServiceClient type
type ProtocolServiceClient struct {
	mock.Mock
}

// BroadcastTransaction provides a mock function with given fields: ctx, req, opts
func (_m *ProtocolServiceClient) BroadcastTransaction(ctx context.Context, req *v1.BroadcastTransactionRequest, opts ...gax.CallOption) (*typesv1.Transaction, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *typesv1.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BroadcastTransactionRequest, ...gax.CallOption) (*typesv1.Transaction, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BroadcastTransactionRequest, ...gax.CallOption) *typesv1.Transaction); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*typesv1.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.BroadcastTransactionRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *ProtocolServiceClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection provides a mock function with given fields:
func (_m *ProtocolServiceClient) Connection() *grpc.ClientConn {
	ret := _m.Called()

	var r0 *grpc.ClientConn
	if rf, ok := ret.Get(0).(func() *grpc.ClientConn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.ClientConn)
		}
	}

	return r0
}

// ConstructTransaction provides a mock function with given fields: ctx, req, opts
func (_m *ProtocolServiceClient) ConstructTransaction(ctx context.Context, req *v1.ConstructTransactionRequest, opts ...gax.CallOption) (*typesv1.Transaction, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *typesv1.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConstructTransactionRequest, ...gax.CallOption) (*typesv1.Transaction, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConstructTransactionRequest, ...gax.CallOption) *typesv1.Transaction); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*typesv1.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ConstructTransactionRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConstructTransferTransaction provides a mock function with given fields: ctx, req, opts
func (_m *ProtocolServiceClient) ConstructTransferTransaction(ctx context.Context, req *v1.ConstructTransferTransactionRequest, opts ...gax.CallOption) (*typesv1.Transaction, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *typesv1.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConstructTransferTransactionRequest, ...gax.CallOption) (*typesv1.Transaction, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConstructTransferTransactionRequest, ...gax.CallOption) *typesv1.Transaction); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*typesv1.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ConstructTransferTransactionRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateFee provides a mock function with given fields: ctx, req, opts
func (_m *ProtocolServiceClient) EstimateFee(ctx context.Context, req *v1.EstimateFeeRequest, opts ...gax.CallOption) (*v1.EstimateFeeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.EstimateFeeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.EstimateFeeRequest, ...gax.CallOption) (*v1.EstimateFeeResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.EstimateFeeRequest, ...gax.CallOption) *v1.EstimateFeeResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.EstimateFeeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.EstimateFeeRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProtocolServiceClient creates a new instance of ProtocolServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProtocolServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProtocolServiceClient {
	mock := &ProtocolServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
